import { HostedEvent } from "@/lib/interfaces/events";

export const pastEvents: HostedEvent[] = [
  {
    id: "fundraiser-2023-mental-health-walk",
    title: "2023 Mental Health Awareness Walk",
    date: "2023-05-14",
    time: "09:00",
    type: "fundraiser",
    description:
      "A community walk to raise awareness and funds for mental health initiatives.",
    location: "Central Park, Cityville",
    image: "/images/events/mental-health-walk-2023.jpg",
  },
  {
    id: "volunteer-2023-food-drive",
    title: "2023 Community Food Drive",
    date: "2023-09-10",
    time: "10:00",
    type: "volunteering",
    description: "Volunteers collected and distributed food to local shelters.",
    location: "Downtown Community Center",
    image: "/images/events/food-drive-2023.jpg",
  },
  {
    id: "fundraiser-2022-gala",
    title: "2022 Annual Charity Gala",
    date: "2022-11-05",
    time: "18:30",
    type: "fundraiser",
    description: "A formal gala event to support mental health programs.",
    location: "Grand Ballroom, City Hotel",
    image: "/images/events/charity-gala-2022.jpg",
  },
  {
    id: "volunteer-2022-cleanup",
    title: "2022 Park Cleanup Day",
    date: "2022-04-22",
    time: "08:00",
    type: "volunteering",
    description: "Volunteers helped clean up the local park and planted trees.",
    location: "Greenfield Park",
    image: "/images/events/park-cleanup-2022.jpg",
  },
  {
    id: "fundraiser-2021-run",
    title: "2021 Run for Hope",
    date: "2021-06-12",
    time: "07:30",
    type: "fundraiser",
    description: "A 5K run to raise funds for youth mental health services.",
    location: "Riverside Track",
    image: "/images/events/run-for-hope-2021.jpg",
  },
  {
    id: "volunteer-2021-helpline",
    title: "2021 Helpline Volunteer Training",
    date: "2021-03-20",
    time: "13:00",
    type: "volunteering",
    description: "Training session for new mental health helpline volunteers.",
    location: "Community Resource Center",
    image: "/images/events/helpline-training-2021.jpg",
  },
  {
    id: "fundraiser-2020-virtual-concert",
    title: "2020 Virtual Benefit Concert",
    date: "2020-09-18",
    time: "19:00",
    type: "fundraiser",
    description:
      "A virtual concert featuring local artists to support mental health outreach.",
    location: "Online",
    image: "/images/events/virtual-concert-2020.jpg",
  },
  {
    id: "volunteer-2020-backpack-drive",
    title: "2020 Backpack Drive",
    date: "2020-08-15",
    time: "11:00",
    type: "volunteering",
    description:
      "Volunteers assembled and distributed backpacks with supplies to students in need.",
    location: "Eastside School Gym",
    image: "/images/events/backpack-drive-2020.jpg",
  },
  {
    id: "fundraiser-2019-golf-tournament",
    title: "2019 Charity Golf Tournament",
    date: "2019-07-20",
    time: "08:00",
    type: "fundraiser",
    description:
      "A charity golf tournament to raise funds for mental health programs.",
    location: "Sunnyvale Golf Club",
    image: "/images/events/golf-tournament-2019.jpg",
  },
  {
    id: "volunteer-2019-shelter-meal",
    title: "2019 Shelter Meal Service",
    date: "2019-12-10",
    time: "17:00",
    type: "volunteering",
    description:
      "Volunteers prepared and served meals at the local homeless shelter.",
    location: "City Shelter Kitchen",
    image: "/images/events/shelter-meal-service-2019.jpg",
  },
  {
    id: "fundraiser-2018-holiday-bazaar",
    title: "2018 Holiday Bazaar",
    date: "2018-12-01",
    time: "10:00",
    type: "fundraiser",
    description:
      "A holiday bazaar featuring local artisans, with proceeds supporting mental health initiatives.",
    location: "Community Center Auditorium",
    image: "/images/events/holiday-bazaar-2018.jpg",
  },
  {
    id: "volunteer-2018-youth-mentoring",
    title: "2018 Youth Mentoring Program Launch",
    date: "2018-09-15",
    time: "14:00",
    type: "volunteering",
    description:
      "Kickoff event for the youth mentoring program, connecting mentors with mentees.",
    location: "Youth Center Main Hall",
    image: "/images/events/youth-mentoring-launch-2018.jpg",
  },
  {
    id: "fundraiser-2017-cook-off",
    title: "2017 Community Cook-Off",
    date: "2017-10-14",
    time: "12:00",
    type: "fundraiser",
    description:
      "A fun cook-off event where local chefs competed, with proceeds supporting mental health services.",
    location: "City Park Pavilion",
    image: "/images/events/community-cook-off-2017.jpg",
  },
  {
    id: "volunteer-2017-senior-visits",
    title: "2017 Senior Center Visits",
    date: "2017-05-20",
    time: "10:00",
    type: "volunteering",
    description:
      "Volunteers visited local senior centers to provide companionship and support.",
    location: "Sunnydale Senior Center",
    image: "/images/events/senior-center-visits-2017.jpg",
  },
  {
    id: "fundraiser-2016-pet-adoption",
    title: "2016 Pet Adoption Fair",
    date: "2016-08-27",
    time: "11:00",
    type: "fundraiser",
    description:
      "A pet adoption fair with local shelters, raising funds for animal welfare and mental health programs.",
    location: "City Animal Shelter",
    image: "/images/events/pet-adoption-fair-2016.jpg",
  },
  {
    id: "volunteer-2016-library-reading",
    title: "2016 Library Reading Program",
    date: "2016-03-12",
    time: "14:00",
    type: "volunteering",
    description:
      "Volunteers read to children at the local library, promoting literacy and community engagement.",
    location: "Downtown Library",
    image: "/images/events/library-reading-program-2016.jpg",
  },
];
